# Generated by Django 3.1 on 2020-10-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prestamo_otorgado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='otorgado',
            new_name='aprobado',
        ),
    ]
